"""initial schema

Revision ID: 458606bbe0a5
Revises: 
Create Date: 2026-09-16 16:10:23.142586
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '458606bbe0a5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('capacity_mw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_location_id'), ['location_id'], unique=True)

    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.String(length=50), nullable=False),
    sa.Column('metrics', sa.String(length=200), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('rows_read', sa.Integer(), nullable=False),
    sa.Column('rows_accepted', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_datasets_facility_id_facilities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_facility_id'), ['facility_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('objective', sa.String(length=20), nullable=False),
    sa.Column('carbon_price_usd_per_tco2e', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dataset_ids', sa.JSON(), nullable=False),
    sa.Column('snapshot_checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_scenarios_facility_id_facilities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenarios'))
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_facility_id'), ['facility_id'], unique=False)

    op.create_table('hourly_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location_id', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('data_status', sa.String(length=50), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('original_timestamp', sa.String(length=64), nullable=False),
    sa.Column('original_timezone', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Float(), nullable=False),
    sa.Column('original_unit', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_hourly_observations_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hourly_observations'))
    )
    with op.batch_alter_table('hourly_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hourly_observations_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index('ix_hourly_observations_lookup', ['dataset_id', 'metric', 'timestamp_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_hourly_observations_timestamp_utc'), ['timestamp_utc'], unique=False)

    op.create_table('optimization_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('solver_status', sa.String(length=30), nullable=False),
    sa.Column('solver_message', sa.String(length=500), nullable=False),
    sa.Column('solver', sa.String(length=100), nullable=False),
    sa.Column('solve_seconds', sa.Float(), nullable=False),
    sa.Column('variables', sa.Integer(), nullable=False),
    sa.Column('constraints', sa.Integer(), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('total_emissions_tco2e', sa.Float(), nullable=False),
    sa.Column('baseline_total_cost_usd', sa.Float(), nullable=True),
    sa.Column('baseline_total_emissions_tco2e', sa.Float(), nullable=True),
    sa.Column('cost_savings_pct', sa.Float(), nullable=True),
    sa.Column('emissions_reduction_pct', sa.Float(), nullable=True),
    sa.Column('hourly', sa.JSON(), nullable=False),
    sa.Column('baseline_allocations', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('constraint_violations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_optimization_results_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_results'))
    )
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_results_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('workloads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('energy_mwh', sa.Float(), nullable=False),
    sa.Column('release_hour', sa.Integer(), nullable=False),
    sa.Column('deadline_hour', sa.Integer(), nullable=False),
    sa.Column('max_mw', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], name=op.f('fk_workloads_scenario_id_scenarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workloads'))
    )
    with op.batch_alter_table('workloads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workloads_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('hourly_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('energy_mwh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['optimization_results.id'], name=op.f('fk_hourly_allocations_result_id_optimization_results'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hourly_allocations'))
    )
    with op.batch_alter_table('hourly_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hourly_allocations_result_id'), ['result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hourly_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hourly_allocations_result_id'))

    op.drop_table('hourly_allocations')
    with op.batch_alter_table('workloads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workloads_scenario_id'))

    op.drop_table('workloads')
    with op.batch_alter_table('optimization_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_results_scenario_id'))

    op.drop_table('optimization_results')
    with op.batch_alter_table('hourly_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hourly_observations_timestamp_utc'))
        batch_op.drop_index('ix_hourly_observations_lookup')
        batch_op.drop_index(batch_op.f('ix_hourly_observations_dataset_id'))

    op.drop_table('hourly_observations')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_facility_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_facility_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_checksum'))

    op.drop_table('datasets')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_location_id'))

    op.drop_table('facilities')
    # ### end Alembic commands ###
